### ISSUE TITLE
/opt/focalboard/bin/focalboard-server: not found

### ISSUE THREAD

**Issue by PPCM** [nicoulaj/focalboard-docker#1]
Hello,

I am trying to run focalboard-docker on a Raspberry Pi 4 cluster over Kuberntes

I configured persistant folders for:
- /opt/focalboard
- /var/lib/focalboard

The POD crashs on start with the error:
/bin/sh: 1: /opt/focalboard/bin/focalboard-server: not found

Any idea?

**Comment by nicoulaj** [comment]
Yes, you should not mount the whole `/opt/focalboard` directory, only `/opt/focalboard/config.json` (see examples in README).
